[platformio]
include_dir  = include
src_dir      = src
default_envs=tinydro

[env:tinydro]
platform=ststm32
framework=stm32cube
board=genericSTM32F407VET6
board_build.f_cpu = 168000000L
board_build.ldscript = stm32f407app.ld
board_upload.maximum_ram_size = 122880
board_upload.maximum_size = 262144
board_upload.offset_address = 0x08020000
upload_protocol=jlink
debug_tool=jlink
monitor_dtr = 1
lib_ldf_mode = chain+
build_flags =
    -std=c++17
    -Wl,-u_printf_float
    -Wno-psabi
    -D USBD_USE_CDC
	-D USBD_VID=0x0483
	-D USBD_PID=0x0003
	-D USB_MANUFACTURER="Unknown"
	-D USB_PRODUCT="\"black_f407ve\""
    -D HSE_VALUE=16000000
    -D PIOVERBOSE=1
#    -D PIO_FRAMEWORK_STM32CUBE_NANOLIB_FLOAT_PRINTF
#    -D PIO_FRAMEWORK_STM32CUBE_NANOLIB_FLOAT_SCANF
build_src_filter =
    +<*.c>
    +<*.cpp>
    -<bootmain.cpp>

[env:tinydro_boot]
platform=ststm32
framework=stm32cube
board=genericSTM32F407VET6
board_build.f_cpu = 168000000L
board_build.ldscript = stm32f407bootloader.ld
upload_protocol=jlink
debug_tool=jlink
monitor_dtr = 1
lib_ldf_mode = chain+
board_upload.maximum_ram_size = 8192
board_upload.maximum_size = 32768
#board_upload.offset_address = 0x08000000
build_flags =
    -std=c++17
    -Wno-psabi
    -D BOOTLOADER
    -D USBD_USE_CDC
	-D USBD_VID=0x0483
	-D USBD_PID=0x0003
	-D USB_MANUFACTURER="Unknown"
	-D USB_PRODUCT="\"black_f407ve\""
    -D HSE_VALUE=16000000
    -D PIOVERBOSE=1
build_src_filter =
    +<bootmain.cpp>
    +<buzzer.cpp>
    +<usbacm.cpp>
    +<usbd_desc.c>
    +<usbd_conf.c>

[env:tinydro2]
platform=ststm32
framework=stm32cube
board=genericSTM32F427VIT6
board_build.f_cpu = 168000000L
upload_protocol=jlink
debug_tool=jlink
monitor_dtr = 1
lib_ldf_mode = chain+
build_flags =
    -std=c++17
    -Wl,-u_printf_float
    -Wno-psabi
    -D USBD_USE_CDC
	-D USBD_VID=0x0483
	-D USBD_PID=0x0003
	-D USB_MANUFACTURER="Unknown"
	-D USB_PRODUCT="\"black_f407ve\""
    -D HSE_VALUE=16000000
    -D PIOVERBOSE=1
    -D BOARD_V2
#    -D PIO_FRAMEWORK_STM32CUBE_NANOLIB_FLOAT_PRINTF
#    -D PIO_FRAMEWORK_STM32CUBE_NANOLIB_FLOAT_SCANF
